
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.history': 'Histoire',
    'nav.visit': 'Visite',
    'nav.gallery': 'Galerie',
    'nav.events': 'Événements',
    'nav.glam': 'GLAM',
    'nav.cultural-areas': 'Aires Culturelles',
    'nav.education': 'Éducation',
    'nav.restaurant': 'Restaurant',
    'nav.accommodation': 'Hébergement',
    'nav.contact': 'Contact',
    'nav.monument': 'Monument',
    
    // Common
    'site.title': 'Monument Paul Biya',
    'site.subtitle': 'Gardien de notre mémoire',
    'language': 'Langue',
    
    // Homepage
    'home.welcome': 'Bienvenue',
    'home.hero.description': 'Bienvenue au Monument Paul Biya, symbole de l\'unité et de la diversité camerounaise. Découvrez un lieu unique où histoire, culture et modernité se rencontrent. Plongez dans l\'expérience !',
    'home.discover': 'Découvrir le Monument',
    'home.plan.visit': 'Planifier ma Visite',
    'home.explore': 'Explorez le Monument',
    'home.stats.height': 'Hauteur du Monument',
    'home.stats.areas': 'Aires Culturelles',
    'home.stats.year': 'Année d\'Inauguration',
    'home.stats.visitors': 'Visiteurs Attendus',
    'home.services': 'Nos Services',
    'home.events': 'Événements à Venir',
    
    // Contact
    'contact.title': 'Contact',
    'contact.hero.description': 'Une question ? Besoin d\'aide ? Contactez notre équipe ou venez nous rendre visite à Sangmélima. Carte interactive et réseaux sociaux à disposition.',
    'contact.stay.connected': 'Restons connectés',
    'contact.coordinates': 'Nos Coordonnées',
    'contact.phone': 'Téléphone',
    'contact.email': 'Email',
    'contact.address': 'Adresse',
    'contact.hours': 'Horaires',
    'contact.send.message': 'Envoyez-nous un Message',
    'contact.location': 'Localisation',
    'contact.follow': 'Suivez-nous',
    'contact.form.name': 'Nom',
    'contact.form.firstname': 'Prénom',
    'contact.form.subject': 'Sujet',
    'contact.form.message': 'Message',
    'contact.form.send': 'Envoyer le Message',
    'contact.address.line1': 'Carrefour MEPHO',
    'contact.address.line2': 'Sangmélima',
    'contact.address.line3': 'Région du Sud',
    'contact.hours.weekdays': 'Lun-Ven: 8h - 18h',
    'contact.hours.weekend': 'Sam-Dim: 9h - 19h',
    'contact.hours.holidays': 'Jours fériés: 10h - 16h',
    'contact.location.description': 'Situé au cœur de Sangmélima, le Monument Paul Biya est facilement accessible par la route et dispose d\'un parking gratuit pour les visiteurs.',
    'contact.social.description': 'Restez connecté pour les dernières actualités et événements',

    // Restaurant
    'restaurant.badge': 'Restaurant La Marraine',
    'restaurant.hero.description': 'Savourez la gastronomie camerounaise dans un cadre prestigieux. Commandes et livraisons à domicile disponibles.',
    'restaurant.flavors.title': 'Saveurs et convivialité',
    'restaurant.flavors.description': 'Découvrez nos spécialités grillées et nos plats traditionnels camerounais préparés avec passion dans notre restaurant La Marraine.',
    'restaurant.orders.title': 'Commandes et Livraisons',
    'restaurant.orders.whatsapp': 'Appels et WhatsApp',
    'restaurant.delivery.available': 'Livraison à domicile disponible',
    'restaurant.menu.title': 'Notre Menu',
    'restaurant.menu.ndole.description': 'Ndole aux crevettes et arachides, plat présidentiel savoureux',
    'restaurant.menu.poulet.description': 'Poulet pané croustillant, spécialité de la maison',
    'restaurant.menu.ndomba.description': 'Poisson d\'eau douce en feuilles de bananier, tradition authentique',
    'restaurant.menu.gombo.description': 'Sauce gombo aux crevettes et légumes frais',
    'restaurant.menu.mbongo.description': 'Sauce mbongo au porc royal, épices traditionnelles',
    'restaurant.menu.porc.description': 'Porc fumé aux épices locales, tendre et savoureux',
    'restaurant.menu.poulet_fume.description': 'Poulet fumé traditionnel, grillé à la perfection',
    'restaurant.menu.bar.price': 'à partir de 4 000 FCFA',
    'restaurant.menu.bar.description': 'Poisson bar frais du jour, grillé ou braisé',
    'restaurant.menu.gambas.description': 'Grosses crevettes grillées aux épices',
    'restaurant.menu.sol.price': '7 000/8 000 FCFA et plus',
    'restaurant.menu.sol.description': 'Poisson Sol frais selon taille et préparation',
    'restaurant.menu.beignets.name': 'Beignets & Omelettes',
    'restaurant.menu.beignets.description': 'Beignets haricots, omelettes garnies au saucisson',
    'restaurant.order.title': 'Commandez maintenant !',
    'restaurant.order.description': 'Appelez-nous pour passer commande ou pour une livraison à domicile',
    'restaurant.order.call': 'Appeler',
    'restaurant.order.whatsapp': 'WhatsApp',
    'restaurant.info.title': 'Informations Pratiques',
    'restaurant.info.hours.title': 'Horaires',
    'restaurant.info.hours.lunch': 'Déjeuner: 12h - 15h',
    'restaurant.info.hours.dinner': 'Dîner: 19h - 23h',
    'restaurant.info.hours.weekend': 'Service continu week-end',
    'restaurant.info.capacity.title': 'Capacité',
    'restaurant.info.capacity.main': 'Salle principale: 120 places',
    'restaurant.info.capacity.terrace': 'Terrasse: 60 places',
    'restaurant.info.capacity.private': 'Salons privés: 40 places',
    'restaurant.info.services.title': 'Services',
    'restaurant.info.services.wifi': 'Wifi gratuit',
    'restaurant.info.services.parking': 'Parking valet',
    'restaurant.info.services.delivery': 'Livraison à domicile',
    'restaurant.info.contact.orders': 'Commandes & Livraisons',
    'restaurant.reservation.title': 'Réservez votre Table',
    'restaurant.reservation.description': 'Garantissez-vous une expérience culinaire exceptionnelle',
    'restaurant.reservation.booking.title': 'Réservation & Commandes',
    'restaurant.reservation.booking.description': 'Appelez-nous pour réserver ou commander',
    'restaurant.reservation.delivery.title': 'Livraison à domicile',
    'restaurant.reservation.delivery.description': 'Service de livraison disponible dans Sangmélima',
    'restaurant.reservation.delivery.button': 'Commander maintenant',

    // Monument
    'monument.badge': 'Architecture Symbolique',
    'monument.hero.description': 'Admirez l\'architecture et la symbolique du Monument Paul Biya. Un chef-d\'œuvre qui célèbre les quatre grandes aires culturelles du Cameroun à travers ses formes et ses décors uniques.',
    'monument.mayor.badge': 'Le Penseur du Monument',
    'monument.mayor.title': 'Hommage au Maire de Sangmélima',
    'monument.mayor.subtitle': 'L\'Inspiration Divine derrière cette Œuvre Majestueuse',
    'monument.mayor.name': 'Monsieur le Maire',
    'monument.mayor.position': 'Maire de Sangmélima',
    'monument.mayor.vision.title': 'Vision et Inspiration',
    'monument.mayor.vision.description1': 'Dans le cœur vibrant de Sangmélima, un homme visionnaire a porté en lui le rêve d\'un monument qui transcenderait les générations. Le Maire de Sangmélima, véritable penseur de cette œuvre dédiée au Chef de l\'État, a su canaliser une inspiration divine pour donner naissance à ce joyau architectural.',
    'monument.mayor.quote': 'Ce monument n\'est pas seulement une structure de béton et d\'acier, c\'est l\'âme du Cameroun qui s\'élève vers les cieux, portant en elle les espoirs et les rêves de notre peuple uni.',
    'monument.mayor.vision.description2': 'Avec une détermination inébranlable et une foi profonde, il a orchestré chaque étape de ce projet titanesque. Ses mains, guidées par une providence divine, ont permis la matérialisation de cette vision grandiose qui honore le Président Paul BIYA et célèbre l\'unité nationale.',
    'monument.mayor.achievements.inspiration.title': 'Inspiration Divine',
    'monument.mayor.achievements.inspiration.description': 'Une vision transcendante guidée par la providence',
    'monument.mayor.achievements.realization.title': 'Concrétisation',
    'monument.mayor.achievements.realization.description': 'Transformation du rêve en réalité tangible',
    'monument.mayor.legacy': 'Aujourd\'hui, ce monument se dresse comme un témoignage éternel de sa vision, de son leadership et de sa dévotion envers la nation camerounaise. Il demeure le symbole vivant d\'une inspiration divine transformée en héritage pour les générations futures.',
    'monument.location.title': 'Localisation du Monument',
    'monument.location.description': 'Découvrez l\'emplacement exact du Monument Paul Biya à Sangmélima',
    'monument.location.gps': 'Coordonnées GPS',
    'monument.location.google_maps': 'Ouvrir dans Google Maps',
    'monument.location.navigate': 'Cliquez pour naviguer vers le monument avec votre application de carte préférée',
    'monument.intro.title': 'Un chef-d\'œuvre architectural',
    'monument.intro.description': 'Admirez l\'architecture et la symbolique du Monument Paul Biya. Un chef-d\'œuvre qui célèbre les quatre grandes aires culturelles du Cameroun à travers ses formes et ses décors uniques.',
    'monument.architect.title': 'Maître d\'Œuvre Architectural',
    'monument.architect.quote': 'Cette œuvre architecturale moderne dialogue avec les traditions ancestrales du Cameroun, créant un symbole d\'unité nationale à travers la diversité culturelle.',
    'monument.architect.name': 'KPOLOM BILONG Dieudonné, Concepteur architectural du Monument et des structures connexes',
    'monument.evolution.title': 'Évolution du Projet',
    'monument.evolution.components.title': 'Composantes du Programme Global',
    'monument.evolution.components.description': 'Évolution des composantes du programme global du monument Paul Biya et ses équipements connexes dans la ville de Sangmélima, de l\'initiative en janvier 2021 aux réalisations concrètes en avril 2025.',
    'monument.evolution.statue.title': 'Statue Monumentale',
    'monument.evolution.statue.description': 'Juste face à l\'entrée principale du monument, Paul BIYA, lui-même admirera ainsi l\'immensité de son parcours et de ses œuvres.',
    'monument.evolution.symbolism.title': 'Symbolisme Architectural',
    'monument.evolution.symbolism.description': 'Le Monument Paul BIYA est matérialisé par une calebasse renversée, signe de sauvegarde des acquis durant le Magistère du Fils Prodigue du Dja et Lobo.',
    'monument.evolution.variants.title': 'Variantes Architecturales',
    'monument.evolution.variants.studies.title': 'Études Architecturales',
    'monument.evolution.variants.studies.description': 'Différentes variantes d\'images initiales du Monument prévues au lieu-dit Ayebe Yekombo et celles reconfigurées pour le lieu-dit MEPHO dans la ville de Sangmélima.',
    'monument.evolution.variants.perspectives.title': 'Perspectives Finales',
    'monument.evolution.variants.perspectives.description': 'Autres variantes d\'images initiales du Monument prévu au lieu-dit Ayebe Yekombo et celles reconfigurées pour le lieu-dit MEPHO dans la ville de Sangmélima.',
    'monument.evolution.equipment.title': 'Équipements Connexes',
    'monument.evolution.equipment.presidential.title': 'Case d\'Accueil Présidentiel',
    'monument.evolution.equipment.presidential.description': 'La Construction d\'une case d\'accueil VVIP conçue et réalisée pour constituer un espace de repos et d\'accueil VIP durant et après la cérémonie d\'inauguration du Monument.',
    'monument.evolution.equipment.boutique.title': 'Bloc Boutique et Snack Bar',
    'monument.evolution.equipment.boutique.description': 'Le bloc boutique et petit snack bar restaurant de la cité décongestionnés de six bungalows aux berges du fleuve Lobo connexes au monument Paul Biya à Sangmélima.',
    'monument.evolution.equipment.municipal.title': 'Modernisation du Cercle Municipal',
    'monument.evolution.equipment.municipal.description': 'Le cercle municipal actuel devrait également être restructuré pour moderniser une salle de fête à proximité du restaurant du boulevard Paul Biya à Sangmélima.',
    'monument.evolution.construction.title': 'Évolution de la Construction',
    'monument.evolution.construction.progress.title': 'Évolution du Chantier',
    'monument.evolution.construction.progress.description': 'Quelques images du chantier dans son évolution entre janvier 2021 et fin avril 2025. Images d\'études et photos des chantiers/extraits des rapports de l\'architecte et maître d\'œuvre.',
    'monument.evolution.construction.finishes.title': 'Finitions et Aménagements',
    'monument.evolution.construction.finishes.description': 'Variantes finales présentant les recollements des VRD, de la clôture, ainsi que de la cage ascenseur donnant sur terrasse panoramique supportant écrans géants au sommet du Monument.',
    'monument.characteristics.title': 'Caractéristiques Architecturales',
    'monument.characteristics.height.title': 'Hauteur Imposante',
    'monument.characteristics.height.value': '42 mètres',
    'monument.characteristics.height.description': 'Une structure majestueuse visible de loin',
    'monument.characteristics.design.title': 'Design Moderne',
    'monument.characteristics.design.value': 'Architecture contemporaine',
    'monument.characteristics.design.description': 'Mélange harmonieux tradition-modernité',
    'monument.characteristics.symbolism.title': 'Symbolisme Culturel',
    'monument.characteristics.symbolism.value': '4 Aires représentées',
    'monument.characteristics.symbolism.description': 'Chaque façade honore une aire culturelle',
    'monument.characteristics.viewpoint.title': 'Point de Vue Panoramique',
    'monument.characteristics.viewpoint.value': '360° sur Sangmélima',
    'monument.characteristics.viewpoint.description': 'Vue imprenable depuis le sommet',
    'monument.characteristics.lighting.title': 'Éclairage Nocturne',
    'monument.characteristics.lighting.value': 'LED multicolore',
    'monument.characteristics.lighting.description': 'Illumination spectaculaire la nuit',
    'monument.characteristics.location.title': 'Emplacement Stratégique',
    'monument.characteristics.location.value': 'Carrefour MEPHO',
    'monument.characteristics.location.description': 'Au cœur de la ville de Sangmélima',
    'monument.cultural_areas.title': 'Les Quatre Aires Culturelles',
    'monument.cultural_areas.sawa.name': 'Aire Sawa',
    'monument.cultural_areas.sawa.description': 'Représentation des peuples côtiers avec leurs traditions maritimes et leur riche patrimoine culturel.',
    'monument.cultural_areas.sawa.symbolism': 'Façade Est du monument',
    'monument.cultural_areas.sawa.colors': 'Bleu océan et blanc',
    'monument.cultural_areas.grassfield.name': 'Aire Grassfield',
    'monument.cultural_areas.grassfield.description': 'Hommage aux hauts plateaux de l\'Ouest avec leurs chefferies traditionnelles et leur artisanat.',
    'monument.cultural_areas.grassfield.symbolism': 'Façade Ouest du monument',
    'monument.cultural_areas.grassfield.colors': 'Vert émeraude et or',
    'monument.cultural_areas.fang_beti.name': 'Aire Fang-Beti',
    'monument.cultural_areas.fang_beti.description': 'Célébration de la forêt équatoriale et des traditions des peuples du Centre et du Sud.',
    'monument.cultural_areas.fang_beti.symbolism': 'Façade Sud du monument',
    'monument.cultural_areas.fang_beti.colors': 'Vert forêt et terre',
    'monument.cultural_areas.sudano.name': 'Aire Soudano-Sahélienne',
    'monument.cultural_areas.sudano.description': 'Représentation du Nord avec ses traditions pastorales et son patrimoine islamique.',
    'monument.cultural_areas.sudano.symbolism': 'Façade Nord du monument',
    'monument.cultural_areas.sudano.colors': 'Ocre et rouge brique',
    'monument.cultural_areas.facade': 'Façade représentative',
    'monument.vision.title': 'Vision Architecturale',
    'monument.vision.quote': 'Le Monument Paul Biya incarne l\'unité dans la diversité. Chaque élément architectural raconte l\'histoire d\'un Cameroun multiple et uni, où les traditions se mêlent à la modernité pour créer une œuvre d\'art vivante au service de la mémoire collective.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.history': 'History',
    'nav.visit': 'Visit',
    'nav.gallery': 'Gallery',
    'nav.events': 'Events',
    'nav.glam': 'GLAM',
    'nav.cultural-areas': 'Cultural Areas',
    'nav.education': 'Education',
    'nav.restaurant': 'Restaurant',
    'nav.accommodation': 'Accommodation',
    'nav.contact': 'Contact',
    'nav.monument': 'Monument',
    
    // Common
    'site.title': 'Paul Biya Monument',
    'site.subtitle': 'Guardian of our memory',
    'language': 'Language',
    
    // Homepage
    'home.welcome': 'Welcome',
    'home.hero.description': 'Welcome to the Paul Biya Monument, symbol of Cameroonian unity and diversity. Discover a unique place where history, culture and modernity meet. Dive into the experience!',
    'home.discover': 'Discover the Monument',
    'home.plan.visit': 'Plan my Visit',
    'home.explore': 'Explore the Monument',
    'home.stats.height': 'Monument Height',
    'home.stats.areas': 'Cultural Areas',
    'home.stats.year': 'Inauguration Year',
    'home.stats.visitors': 'Expected Visitors',
    'home.services': 'Our Services',
    'home.events': 'Upcoming Events',
    
    // Contact
    'contact.title': 'Contact',
    'contact.hero.description': 'A question? Need help? Contact our team or come visit us in Sangmélima. Interactive map and social networks available.',
    'contact.stay.connected': 'Let\'s stay connected',
    'contact.coordinates': 'Our Coordinates',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.hours': 'Hours',
    'contact.send.message': 'Send us a Message',
    'contact.location': 'Location',
    'contact.follow': 'Follow us',
    'contact.form.name': 'Name',
    'contact.form.firstname': 'First Name',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.address.line1': 'MEPHO Crossroads',
    'contact.address.line2': 'Sangmélima',
    'contact.address.line3': 'South Region',
    'contact.hours.weekdays': 'Mon-Fri: 8am - 6pm',
    'contact.hours.weekend': 'Sat-Sun: 9am - 7pm',
    'contact.hours.holidays': 'Holidays: 10am - 4pm',
    'contact.location.description': 'Located in the heart of Sangmélima, the Paul Biya Monument is easily accessible by road and has free parking for visitors.',
    'contact.social.description': 'Stay connected for the latest news and events',

    // Restaurant
    'restaurant.badge': 'Restaurant La Marraine',
    'restaurant.hero.description': 'Savor Cameroonian gastronomy in a prestigious setting. Orders and home delivery available.',
    'restaurant.flavors.title': 'Flavors and conviviality',
    'restaurant.flavors.description': 'Discover our grilled specialties and traditional Cameroonian dishes prepared with passion in our restaurant La Marraine.',
    'restaurant.orders.title': 'Orders and Deliveries',
    'restaurant.orders.whatsapp': 'Calls and WhatsApp',
    'restaurant.delivery.available': 'Home delivery available',
    'restaurant.menu.title': 'Our Menu',
    'restaurant.menu.ndole.description': 'Ndole with shrimp and peanuts, savory presidential dish',
    'restaurant.menu.poulet.description': 'Crispy breaded chicken, house specialty',
    'restaurant.menu.ndomba.description': 'Freshwater fish in banana leaves, authentic tradition',
    'restaurant.menu.gombo.description': 'Okra sauce with shrimp and fresh vegetables',
    'restaurant.menu.mbongo.description': 'Mbongo sauce with royal pork, traditional spices',
    'restaurant.menu.porc.description': 'Smoked pork with local spices, tender and flavorful',
    'restaurant.menu.poulet_fume.description': 'Traditional smoked chicken, grilled to perfection',
    'restaurant.menu.bar.price': 'from 4 000 FCFA',
    'restaurant.menu.bar.description': 'Fresh daily bass, grilled or braised',
    'restaurant.menu.gambas.description': 'Large grilled prawns with spices',
    'restaurant.menu.sol.price': '7 000/8 000 FCFA and more',
    'restaurant.menu.sol.description': 'Fresh Sol fish according to size and preparation',
    'restaurant.menu.beignets.name': 'Fritters & Omelettes',
    'restaurant.menu.beignets.description': 'Bean fritters, omelettes with sausage',
    'restaurant.order.title': 'Order now!',
    'restaurant.order.description': 'Call us to place an order or for home delivery',
    'restaurant.order.call': 'Call',
    'restaurant.order.whatsapp': 'WhatsApp',
    'restaurant.info.title': 'Practical Information',
    'restaurant.info.hours.title': 'Hours',
    'restaurant.info.hours.lunch': 'Lunch: 12pm - 3pm',
    'restaurant.info.hours.dinner': 'Dinner: 7pm - 11pm',
    'restaurant.info.hours.weekend': 'Continuous service weekend',
    'restaurant.info.capacity.title': 'Capacity',
    'restaurant.info.capacity.main': 'Main hall: 120 seats',
    'restaurant.info.capacity.terrace': 'Terrace: 60 seats',
    'restaurant.info.capacity.private': 'Private rooms: 40 seats',
    'restaurant.info.services.title': 'Services',
    'restaurant.info.services.wifi': 'Free wifi',
    'restaurant.info.services.parking': 'Valet parking',
    'restaurant.info.services.delivery': 'Home delivery',
    'restaurant.info.contact.orders': 'Orders & Deliveries',
    'restaurant.reservation.title': 'Reserve your Table',
    'restaurant.reservation.description': 'Guarantee yourself an exceptional culinary experience',
    'restaurant.reservation.booking.title': 'Reservation & Orders',
    'restaurant.reservation.booking.description': 'Call us to book or order',
    'restaurant.reservation.delivery.title': 'Home delivery',
    'restaurant.reservation.delivery.description': 'Delivery service available in Sangmélima',
    'restaurant.reservation.delivery.button': 'Order now',

    // Monument
    'monument.badge': 'Symbolic Architecture',
    'monument.hero.description': 'Admire the architecture and symbolism of the Paul Biya Monument. A masterpiece that celebrates the four major cultural areas of Cameroon through its unique forms and decorations.',
    'monument.mayor.badge': 'The Thinker of the Monument',
    'monument.mayor.title': 'Tribute to the Mayor of Sangmélima',
    'monument.mayor.subtitle': 'The Divine Inspiration behind this Majestic Work',
    'monument.mayor.name': 'Mr. Mayor',
    'monument.mayor.position': 'Mayor of Sangmélima',
    'monument.mayor.vision.title': 'Vision and Inspiration',
    'monument.mayor.vision.description1': 'In the vibrant heart of Sangmélima, a visionary man carried within him the dream of a monument that would transcend generations. The Mayor of Sangmélima, true thinker of this work dedicated to the Head of State, was able to channel divine inspiration to give birth to this architectural jewel.',
    'monument.mayor.quote': 'This monument is not just a structure of concrete and steel, it is the soul of Cameroon rising to the heavens, carrying within it the hopes and dreams of our united people.',
    'monument.mayor.vision.description2': 'With unwavering determination and deep faith, he orchestrated every step of this titanic project. His hands, guided by divine providence, allowed the materialization of this grandiose vision that honors President Paul BIYA and celebrates national unity.',
    'monument.mayor.achievements.inspiration.title': 'Divine Inspiration',
    'monument.mayor.achievements.inspiration.description': 'A transcendent vision guided by providence',
    'monument.mayor.achievements.realization.title': 'Realization',
    'monument.mayor.achievements.realization.description': 'Transformation of dream into tangible reality',
    'monument.mayor.legacy': 'Today, this monument stands as an eternal testimony to his vision, his leadership and his devotion to the Cameroonian nation. It remains the living symbol of divine inspiration transformed into heritage for future generations.',
    'monument.location.title': 'Monument Location',
    'monument.location.description': 'Discover the exact location of the Paul Biya Monument in Sangmélima',
    'monument.location.gps': 'GPS Coordinates',
    'monument.location.google_maps': 'Open in Google Maps',
    'monument.location.navigate': 'Click to navigate to the monument with your preferred map application',
    'monument.intro.title': 'An architectural masterpiece',
    'monument.intro.description': 'Admire the architecture and symbolism of the Paul Biya Monument. A masterpiece that celebrates the four major cultural areas of Cameroon through its unique forms and decorations.',
    'monument.architect.title': 'Architectural Project Manager',
    'monument.architect.quote': 'This modern architectural work dialogues with the ancestral traditions of Cameroon, creating a symbol of national unity through cultural diversity.',
    'monument.architect.name': 'KPOLOM BILONG Dieudonné, Architectural designer of the Monument and related structures',
    'monument.evolution.title': 'Project Evolution',
    'monument.evolution.components.title': 'Global Program Components',
    'monument.evolution.components.description': 'Evolution of the components of the global program of the Paul Biya monument and its related equipment in the city of Sangmélima, from the initiative in January 2021 to concrete achievements in April 2025.',
    'monument.evolution.statue.title': 'Monumental Statue',
    'monument.evolution.statue.description': 'Right in front of the main entrance of the monument, Paul BIYA himself will thus admire the immensity of his journey and his works.',
    'monument.evolution.symbolism.title': 'Architectural Symbolism',
    'monument.evolution.symbolism.description': 'The Paul BIYA Monument is materialized by an inverted calabash, sign of safeguarding the achievements during the Magistracy of the Prodigal Son of Dja and Lobo.',
    'monument.evolution.variants.title': 'Architectural Variants',
    'monument.evolution.variants.studies.title': 'Architectural Studies',
    'monument.evolution.variants.studies.description': 'Different variants of initial images of the Monument planned at the place called Ayebe Yekombo and those reconfigured for the place called MEPHO in the city of Sangmélima.',
    'monument.evolution.variants.perspectives.title': 'Final Perspectives',
    'monument.evolution.variants.perspectives.description': 'Other variants of initial images of the Monument planned at the place called Ayebe Yekombo and those reconfigured for the place called MEPHO in the city of Sangmélima.',
    'monument.evolution.equipment.title': 'Related Equipment',
    'monument.evolution.equipment.presidential.title': 'Presidential Reception House',
    'monument.evolution.equipment.presidential.description': 'The construction of a VVIP reception house designed and built to constitute a rest and VIP reception space during and after the inauguration ceremony of the Monument.',
    'monument.evolution.equipment.boutique.title': 'Boutique and Snack Bar Block',
    'monument.evolution.equipment.boutique.description': 'The boutique block and small snack bar restaurant of the city decongested from six bungalows on the banks of the Lobo River connected to the Paul Biya monument in Sangmélima.',
    'monument.evolution.equipment.municipal.title': 'Municipal Circle Modernization',
    'monument.evolution.equipment.municipal.description': 'The current municipal circle should also be restructured to modernize a party hall near the restaurant on Paul Biya boulevard in Sangmélima.',
    'monument.evolution.construction.title': 'Construction Evolution',
    'monument.evolution.construction.progress.title': 'Construction Site Evolution',
    'monument.evolution.construction.progress.description': 'Some images of the construction site in its evolution between January 2021 and end of April 2025. Study images and photos of construction sites/extracts from architect and project manager reports.',
    'monument.evolution.construction.finishes.title': 'Finishes and Fittings',
    'monument.evolution.construction.finishes.description': 'Final variants showing the reconciliation of utilities, fencing, as well as the elevator shaft leading to the panoramic terrace supporting giant screens at the top of the Monument.',
    'monument.characteristics.title': 'Architectural Characteristics',
    'monument.characteristics.height.title': 'Imposing Height',
    'monument.characteristics.height.value': '42 meters',
    'monument.characteristics.height.description': 'A majestic structure visible from afar',
    'monument.characteristics.design.title': 'Modern Design',
    'monument.characteristics.design.value': 'Contemporary architecture',
    'monument.characteristics.design.description': 'Harmonious blend of tradition and modernity',
    'monument.characteristics.symbolism.title': 'Cultural Symbolism',
    'monument.characteristics.symbolism.value': '4 Areas represented',
    'monument.characteristics.symbolism.description': 'Each facade honors a cultural area',
    'monument.characteristics.viewpoint.title': 'Panoramic Viewpoint',
    'monument.characteristics.viewpoint.value': '360° over Sangmélima',
    'monument.characteristics.viewpoint.description': 'Breathtaking view from the top',
    'monument.characteristics.lighting.title': 'Night Lighting',
    'monument.characteristics.lighting.value': 'Multicolor LED',
    'monument.characteristics.lighting.description': 'Spectacular illumination at night',
    'monument.characteristics.location.title': 'Strategic Location',
    'monument.characteristics.location.value': 'MEPHO Crossroads',
    'monument.characteristics.location.description': 'In the heart of Sangmélima city',
    'monument.cultural_areas.title': 'The Four Cultural Areas',
    'monument.cultural_areas.sawa.name': 'Sawa Area',
    'monument.cultural_areas.sawa.description': 'Representation of coastal peoples with their maritime traditions and rich cultural heritage.',
    'monument.cultural_areas.sawa.symbolism': 'East facade of the monument',
    'monument.cultural_areas.sawa.colors': 'Ocean blue and white',
    'monument.cultural_areas.grassfield.name': 'Grassfield Area',
    'monument.cultural_areas.grassfield.description': 'Tribute to the western highlands with their traditional chieftaincies and craftsmanship.',
    'monument.cultural_areas.grassfield.symbolism': 'West facade of the monument',
    'monument.cultural_areas.grassfield.colors': 'Emerald green and gold',
    'monument.cultural_areas.fang_beti.name': 'Fang-Beti Area',
    'monument.cultural_areas.fang_beti.description': 'Celebration of the equatorial forest and traditions of the peoples of the Center and South.',
    'monument.cultural_areas.fang_beti.symbolism': 'South facade of the monument',
    'monument.cultural_areas.fang_beti.colors': 'Forest green and earth',
    'monument.cultural_areas.sudano.name': 'Sudano-Sahelian Area',
    'monument.cultural_areas.sudano.description': 'Representation of the North with its pastoral traditions and Islamic heritage.',
    'monument.cultural_areas.sudano.symbolism': 'North facade of the monument',
    'monument.cultural_areas.sudano.colors': 'Ochre and brick red',
    'monument.cultural_areas.facade': 'Representative facade',
    'monument.vision.title': 'Architectural Vision',
    'monument.vision.quote': 'The Paul Biya Monument embodies unity in diversity. Each architectural element tells the story of a multiple and united Cameroon, where traditions blend with modernity to create a living work of art serving collective memory.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
